name: PollenViability
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.3
  - pip=19.1
  - tensorflow=1.14.0
  - pandas=0.25.1
  - numpy=1.16.5
  - pillow=6.1.0
  - opencv=3.4.2
  - plotly=4.1.0
  - plotly::plotly-orca
  - psutil=5.6.2
  - jupyterlab
  - scikit-learn
  - pip:
    - image-slicer==0.3.0